// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Redacao.Avaliacao.Data;

namespace Redacao.Avaliacao.Data.Migrations
{
    [DbContext(typeof(AvaliacaoContext))]
    [Migration("20200331005759_Initial Avaliacao")]
    partial class InitialAvaliacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Redacao.Avaliacao.Domain.Entities.AvaliacaoProfessor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Observacao")
                        .HasMaxLength(250);

                    b.Property<int>("QualidadeCorrecao");

                    b.Property<Guid>("RedacaoId");

                    b.Property<Guid>("UsuarioProfessorId");

                    b.HasKey("Id");

                    b.HasIndex("RedacaoId");

                    b.HasIndex("UsuarioProfessorId");

                    b.ToTable("AvaliacaoProfessor");
                });

            modelBuilder.Entity("Redacao.Avaliacao.Domain.Entities.AvaliacaoRedacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnotacaoCriterio01")
                        .HasMaxLength(100);

                    b.Property<string>("AnotacaoCriterio02")
                        .HasMaxLength(100);

                    b.Property<string>("AnotacaoCriterio03")
                        .HasMaxLength(100);

                    b.Property<string>("Feedback")
                        .HasMaxLength(100);

                    b.Property<int>("NotaCriterio01");

                    b.Property<int>("NotaCriterio02");

                    b.Property<int>("NotaCriterio03");

                    b.Property<string>("PontosFortes")
                        .HasMaxLength(100);

                    b.Property<string>("PontosFracos")
                        .HasMaxLength(100);

                    b.Property<Guid>("RedacaoId");

                    b.Property<Guid>("UsuarioAlunoId");

                    b.HasKey("Id");

                    b.HasIndex("RedacaoId");

                    b.HasIndex("UsuarioAlunoId");

                    b.ToTable("AvaliacaoRedacao");
                });
#pragma warning restore 612, 618
        }
    }
}
